config/routes.rb
Rails.application.routes.draw do

   root 'listings#index'
   resources :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	def index
		@listings = Listing.all
	end

	def new
		@listing = Listing.new
	end

	def create
		#binding.pry
		@listing = Listing.new(listing_params)
		if @listing.save
			redirect_to listings_path
		else
			render :new
		end
	end
	def edit
		@listing = Listing.find(params[:id])
	end
	def update
		@listing = Listing.find(params[:id])
		if @listing.update(listing_params)
			redirect_to listings_path
		else
			render :edit
		end
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def destroy
		#binding.pry
		@listing = Listing.find(params[:id])
		@listing.destroy
		redirect_to listings_path
	end
	private

	def listing_params
		params.require(:listing).permit(:description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class ="container" id="clearfix">
   <%= yield %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<%if obj.errors.any? %>
  <h4>Please correct the errors below</h4>
  <%obj.errors.full_messages.each do |msg|%>
    <ul>
	    <li>
	    	<%=msg%>
	    </li>
    </ul>
  <%end%>  
<%end%>

<%=form_for obj do |f|%>
  <p>
  	<%=f.label :description%>
    <%=f.text_field :description%>
  </p>
  <p>
  	<%=f.submit "Submit"%>
  </p>  
    
<%end%>
<%= link_to "Back", listings_path%>

app/views/listings/edit.html.erb
<h2> Edit your todo item</h2>

<%= render 'form', obj: @listing%>

app/views/listings/index.html.erb
<h1> Todos</h1>
<div>
  <% @listings.each do |listing|%>
      <ul>
        <li>
          <%= link_to listing.description, listing_path(listing)%>
        </li>
        <ul>
          <li>
            <%= link_to "Edit todo", edit_listing_path(listing)%>
          </li>
        </ul>
        <ul>
          <li>
            <%= link_to "[Delete Todo]", listing, method: :delete, data: {confirm: "Are you sure ?"} %>
          </li>
        </ul>
      </ul>
  <%end%>

  <%= link_to "Create a new todo", new_listing_path %>
</div>

app/views/listings/new.html.erb
<h2> Add a todo item</h2>

<%= render 'form', obj: @listing%>

app/views/listings/show.html.erb
<h1>View your Todo</h1>

<p><%=@listing.description%></p>
<p><%=link_to "Edit Todo", edit_listing_path(@listing)%></p>
<p><%=link_to "Back to Todo list", listings_path%></p>